name: Java CI with JDK 17

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile Java
      run: javac -d out src/**/*.java

    - name: Run tests
      run: java -cp out -Dtest=src/test/**/*.java org.junit.platform.launcher.Launcher --select-resolver=junit-platform --scan-class-path

    - name: Build JAR
      run: jar -cfm Assistant2.jar Manifest.txt -C out .

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Assistant2
        path: Assistant2.jar
